### ISSUE TITLE
pelias-pip remains in CrashLoopBackOff

### ISSUE THREAD

**Issue by arne-cl** [pelias/kubernetes#79]
I am trying to get pelias running on kubernetes. As I'm not allowed to run `helm install`,
I installed pelias manually (using `kubectl apply` with the files that `helm template` would generate).

`pelias-pip` is often in `CrashLoopBackOff` status.

```
$ kubectl-1.8.15 -n geocoding-staging describe pod pelias-pip-3387644077-8bj7n
[...]
  Normal   Created     25m                 kubelet, dep-kprodv2-100  Created container with id 759fcad828774a090ad9fd6867d89f7da67e0e731705420fc3fa5cdeeb380931
  Normal   Started     25m                 kubelet, dep-kprodv2-100  Started container with id 759fcad828774a090ad9fd6867d89f7da67e0e731705420fc3fa5cdeeb380931
  Warning  BackOff     24m (x14 over 27m)  kubelet, dep-kprodv2-100  Back-off restarting failed container
  Warning  FailedSync  24m (x7 over 25m)   kubelet, dep-kprodv2-100  Error syncing pod, skipping: failed to "StartContainer" for "pelias-pip" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=pelias-pip pod=pelias-pip-33
87644077-8bj7n_geocoding-staging(efb45eba-7655-11e9-b0f2-901b0efcedbb)"
```

The logs of the initContainer showed that the dowload was successful:

```
$ kubectl-1.8.15 -n geocoding-staging logs -f pelias-pip-3387644077-8bj7n -c download
[...]
Downloading whosonfirst-data-admin-zw-latest.db.bz2                                                                                                                                                                                          
done downloading whosonfirst-data-admin-zw-latest.db.bz2                                                                                                                                                                                     
done downloading whosonfirst-data-admin-zm-latest.db.bz2                                                                                                                                                                                     
done downloading whosonfirst-data-admin-us-latest.db.bz2                                                                                                                                                                                     
done downloading whosonfirst-data-latest.db.bz2                                                                                                                                                                                              
All done!
```

but the pelias-pip logs show a `SqliteError: disk I/O error`. I'm using `emptyDir` for the data volume,
so I don't know how this could happen. Any ideas?

```
$ kubectl-1.8.15 -n geocoding-staging logs pelias-pip-3146733653-rr5ds
{"level":"info","message":"starting with layers neighbourhood,borough,locality,localadmin,county,macrocounty,macroregion,region,dependency,country,empire,continent,marinearea,ocean","label":"wof-pip-service:master","timestamp":"2019-05-14T10:01:52.033Z"}
pip-service is now running on port 3102
{"level":"info","message":"marinearea worker loaded 305 features in 87.217 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:21.489Z"}
{"level":"info","message":"borough worker loaded 273 features in 87.512 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:21.580Z"}
{"level":"info","message":"ocean worker loaded 7 features in 87.427 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:21.705Z"}
{"level":"info","message":"dependency worker loaded 40 features in 88.31 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:22.506Z"}
{"level":"info","message":"empire worker loaded 11 features in 89.299 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:23.491Z"}
{"level":"info","message":"macroregion worker loaded 94 features in 90.313 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:24.595Z"}
{"level":"info","message":"continent worker loaded 8 features in 90.979 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:25.283Z"}
{"level":"info","message":"macrocounty worker loaded 477 features in 92.131 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:26.398Z"}
{"level":"info","message":"country worker loaded 210 features in 93.094 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:27.108Z"}
{"level":"info","message":"region worker loaded 4175 features in 97.457 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:31.625Z"}
{"level":"info","message":"neighbourhood worker loaded 29316 features in 107.278 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:03:41.731Z"}
{"level":"info","message":"136.243.46.254 - - [14/May/2019:10:03:59 +0000] \"GET /12/12 HTTP/1.1\" - - \"-\" \"Go-http-client/1.1\"","label":"pip","timestamp":"2019-05-14T10:03:59.062Z"}
{"level":"info","message":"county worker loaded 40797 features in 128.074 seconds","label":"wof-pip-service:master","timestamp":"2019-05-14T10:04:02.458Z"}
{"level":"info","message":"136.243.46.254 - - [14/May/2019:10:04:09 +0000] \"GET /12/12 HTTP/1.1\" - - \"-\" \"Go-http-client/1.1\"","label":"pip","timestamp":"2019-05-14T10:04:09.056Z"}

/code/pelias/pip-service/node_modules/pelias-whosonfirst/src/components/sqliteStream.js:25
      const elt = this._iterator.next();
                                 ^
SqliteError: disk I/O error
    at SQLiteStream._read (/code/pelias/pip-service/node_modules/pelias-whosonfirst/src/components/sqliteStream.js:25:34)
    at SQLiteStream.Readable.read (_stream_readable.js:452:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
{"level":"error","message":"locality worker exited unexpectedly with code 1, signal null","label":"wof-pip-service:master","timestamp":"2019-05-14T10:04:10.968Z"}
{"level":"info","message":"neighbourhood worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.970Z"}
{"level":"info","message":"continent worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.970Z"}
{"level":"info","message":"dependency worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.970Z"}
{"level":"info","message":"macrocounty worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.971Z"}
{"level":"info","message":"county worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.971Z"}
{"level":"info","message":"region worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.971Z"}
{"level":"info","message":"country worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.971Z"}
{"level":"info","message":"borough worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.972Z"}
{"level":"info","message":"macroregion worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.972Z"}
{"level":"info","message":"empire worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.972Z"}
{"level":"info","message":"ocean worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.976Z"}
{"level":"info","message":"marinearea worker process exiting, stats: {\"calls\":0,\"hits\":0,\"misses\":0}","label":"admin-lookup:worker","timestamp":"2019-05-14T10:04:10.977Z"}

/code/pelias/pip-service/node_modules/pelias-wof-admin-lookup/src/pip/index.js:166
        throw `${layer} worker shutdown unexpectedly`;
        ^
locality worker shutdown unexpectedly
```

**Comment by arne-cl** [comment]
Out of curiosity, I tried to install `pelias-pip` again (after making sure the deployment/service/pod was deleted), this time with its own PVC instead of an `emptyDir` volume.

Now, the pod gets into a crash loop earlier when attempting to create `/data/whosonfirst`:

```
$ kubectl-1.8.15 -n geocoding-staging logs pelias-pip-1688495683-5cw0v -c download
/code/pelias/pip-service/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45
        throw err0
        ^

Error: EACCES: permission denied, mkdir '/data/whosonfirst'
    at Object.mkdirSync (fs.js:753:3)
    at mkdirsSync (/code/pelias/pip-service/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
    at Object.mkdirsSync (/code/pelias/pip-service/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:36:14)
    at download (/code/pelias/pip-service/node_modules/pelias-whosonfirst/utils/sqlite_download.js:15:6)
    at Object.<anonymous> (/code/pelias/pip-service/node_modules/pelias-whosonfirst/utils/download_data.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
This happens, although the pod has its own PVC.
```
$ kubectl-1.8.15 -n geocoding-staging get deployments,pods,pvc | ag "NAME|pip"
NAME                             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/pelias-pip                1         1         1            0           15m

NAME                                         READY     STATUS                  RESTARTS   AGE
po/pelias-pip-1688495683-5cw0v               0/1       Init:CrashLoopBackOff   7          15m

NAME                                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                          AGE
pvc/pelias-pip-staging-pvc             Bound     pvc-736d59cf-7ae0-11e9-b050-901b0e8d9c59   10Gi       RWO            storageclass-generic-ceph-pv-prodv2   15m
```

Here's the complete Kubernetes config file `pelias-pip.yaml`:

```
---
# Source: pelias/templates/pip-pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pelias-pip-staging-pvc
  annotations:
spec:
  storageClassName: storageclass-generic-ceph-pv-prodv2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Source: pelias/templates/pip-deployment.tpl

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pelias-pip
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pelias-pip
      annotations:
    spec:
      initContainers:
        - name: download
          image: pelias/pip-service:latest
          command: ["./bin/download", "--admin-only"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
          resources:
            limits:
              memory: 3Gi
              cpu: 3 # template used 4 CPUs, but in our cluster: initContainer resources <= container resources
            requests:
              memory: 1Gi
              cpu: 0.1
      containers:
        - name: pelias-pip
          image: pelias/pip-service:latest
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
          resources:
            limits:
              memory: 15Gi
              cpu: 3
            requests:
              memory: 10Gi
              cpu: 0.1
          readinessProbe:
            httpGet:
              path: /12/12
              port: 3102
            initialDelaySeconds: 120 #PIP service takes a long time to start up
      volumes:
        - name: config-volume
          configMap:
            name: pelias-json-configmap
            items:
              - key: pelias.json
                path: pelias.json
        - name: data-volume
          persistentVolumeClaim:
            claimName: pelias-pip-staging-pvc
```

**Comment by orangejulius** [comment]
Hm, I have never used a PVC with the PIP service so unfortunately can't comment on whether or not that works. My hope/understanding was that there wouldn't be a detectable difference inside the container. It looks like that might not be true.

As for the error you saw with the emptyDir, (`SqliteError: disk I/O error`), my understanding is that error is fairly generic. The WOF data is pretty big, is it possible there wasn't enough disk space on the machine? I think 20-30GB is a good minimum.

**Comment by arne-cl** [comment]
Dear Julian,

I managed to get it working with a 50GB PVC and this workaround:

```
[...]
    spec:
      securityContext:
        fsGroup: 1000 # workaround to enable user 'pelias' to create /data/whosonfirst
      initContainers:
        - name: download
          image: pelias/pip-service:latest
          [...]
```

If I understand it correctly, `fsGroup: 1000` means that the user "creating" any of the `volumeMounts` automatically belongs to the group with the GID 1000 (here: pelias). I will let you know once I find a proper solution.

As for the `emptyDir` case, I can no longer reproduce the issue.
