### ISSUE TITLE
Pods running even if disabled

### ISSUE THREAD

**Issue by mkozjak** [pelias/kubernetes#85]
Some of our pods are running even though they are disabled in config:

```sh
pelias-api-5566d6f997-xt8hl            1/1       Running            0          10m
pelias-libpostal-6857cdbdf8-rjckp      1/1       Running            1          10m
pelias-placeholder-79977fd7f9-qw2p9    1/1       Running            0          10m
```

Full config:
```
elasticsearch:
  host: "some.host.io"
  port: 9211
  protocol: "https"
  auth: "foo:bar"

## API settings
api:
  replicas: 1
  canaryReplicas: 0
  dockerTag: "latest"
  canaryDockerTag: null # set this value to enable the canary deployment
  indexName: "pelias"
  attributionURL: "http://api.yourpelias.com/attribution"
  # Whether the API service should be externally accessible
  # Set this to true if you want to, for example on AWS, set up an ELB for the API
  externalService: false
  # whether the external service  should be internet facing or private (default private)
  privateLoadBalancer: false
  accessLog: "common" # allows configuring access log format. Empty string disables access log
  autocomplete:
    exclude_address_length: 0
  requests:
    memory: 0.25Gi
    cpu: 0.1
  minReadySeconds: 10
  annotations: {}

placeholder:
  enabled: false
  replicas: 1
  host: "http://pelias-placeholder-service:3000/"
  dockerTag: "latest"
  storeURL: "https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/store.sqlite3.gz"
  cpus: 1 # how many CPUs to allow using via the npm `cluster2` module
  retries: 1 # number of time the API will retry requests to placeholder
  timeout: 5000 # time in ms the API will wait for placeholder responses
  annotations: {}

libpostal:
  enabled: false
  replicas: 1
  host: "http://pelias-libpostal-service:4400/"
  dockerTag: "latest"
  retries: 1 # number of time the API will retry requests to libpostal
  timeout: 5000 # time in ms the API will wait for libpostal responses
  annotations: {}

interpolation:
  enabled: false
  replicas: 1
  host: "http://pelias-interpolation-service:3000/"
  dockerTag: "latest"
  # URL prefix of location where streets.db and address.db will be downloaded
  downloadPath: " https://s3.amazonaws.com/pelias-data.nextzen.org/interpolation/current"
  retries: 1 # number of time the API will retry requests to interpolation service
  timeout: 5000 # time in ms the API will wait for interpolation service responses
  annotations: {}
  pvc: {}
#    create: true
#    name: interpolation-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}

pip:
  enabled: false
  replicas: 1
  host: "http://pelias-pip-service:3102/"
  dockerTag: "latest"
  maxUnavailable: 0 # adjusts rolling update settings
  retries: 1 # number of time the API will retry requests to the pip service
  timeout: 5000 # time in ms the API will wait for pip service responses
  annotations: {}
  pvc: {}
#    create: true
#    name: pip-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}

dashboard:
  enabled: false
  replicas: 1
  dockerTag: "latest"
  domain: null # set this to enable an ingress

# Deprecated fields
# pipEnabled: true
# pipHost: "http://pelias-pip-service:3102/"

# interpolationEnabled: false
# interpolationHost: "http://pelias-interpolation-service:3000/"

# Importer settings
whosonfirst:
  sqlite: false
  dataHost: null
```

So in this case, according to #44, `libpostal` and `placeholder` shouldn't be running, right?

Installed latest version by running:
```helm install /tmp/pelias --name pelias --namespace default --values pelias.yaml```
where `/tmp/pelias` is tracking `e15e09e7e62aa4b482ed52245ef9fc9507e2898e`.
